version: "3.9"

services:
  cappuccino:
    image: ghcr.io/thereverend403/cappuccino:main
    container_name: cappuccino
    restart: unless-stopped
    init: true
    read_only: true
    user: ${PUID:-1000}:${PGID:-1000}
    env_file: .env
    environment:
      CFG_BOT_ADMIN: ${CFG_BOT_ADMIN:-}
      CFG_BOT_NICK: ${CFG_BOT_NICK:?}
      CFG_BOT_REALNAME: ${CFG_BOT_REALNAME:?}
      CFG_BOT_USERNAME: ${CFG_BOT_USERNAME:?}
      CFG_DB_URI: ${CFG_DB_URI:?}
      CFG_IRC_HOST: ${CFG_IRC_HOST:?}
      CFG_IRC_PORT: ${CFG_IRC_PORT:-6697}
      CFG_IRC_SSL: ${CFG_IRC_SSL:-true}
      CFG_LASTFM_API_KEY: ${CFG_LASTFM_API_KEY:-}
      CFG_NICKSERV_PASSWORD: ${CFG_NICKSERV_PASSWORD:-}
      CFG_SENTRY_DSN: ${CFG_SENTRY_DSN:-}
      CFG_INFLUX_URL: ${CFG_INFLUX_URL:-}
      CFG_INFLUX_TOKEN: ${CFG_INFLUX_TOKEN:-}
      CFG_INFLUX_BUCKET: ${CFG_INFLUX_BUCKET:-}
      CFG_INFLUX_ORG: ${CFG_INFLUX_ORG:-}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/postgresql:/run/postgresql
      - ${BASE_DIR:?}/config:/config
    tmpfs:
      - /tmp
    networks:
      - cappuccino
      - caddy
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT:-0}
          memory: ${MEM_LIMIT:-0}

networks:
  cappuccino:
    name: cappuccino
  caddy:
    external: true
