version: '3.9'

services:
  cappuccino:
    image: ghcr.io/thereverend403/cappuccino:latest
    container_name: cappuccino
    volumes:
      - ${BASE_DIR:?}/config:/config
      - ${BASE_DIR:?}/data:/data
      - /etc/localtime:/etc/localtime:ro
    tmpfs: /run:exec
    ports:
      - 127.0.0.1:1337:1337
    environment:
      CFG_BOT_ADMIN: ${CFG_BOT_ADMIN:-}
      CFG_BOT_NICK: ${CFG_BOT_NICK:?}
      CFG_BOT_REALNAME: ${CFG_BOT_REALNAME:?}
      CFG_BOT_USERNAME: ${CFG_BOT_USERNAME:?}
      CFG_DB_HOST: ${CFG_DB_HOST:?}
      CFG_DB_NAME: ${CFG_DB_NAME:?}
      CFG_DB_PASSWORD: ${CFG_DB_PASSWORD:?}
      CFG_DB_PORT: ${CFG_DB_PORT:-5432}
      CFG_DB_USER: ${CFG_DB_USER:?}
      CFG_IRC_HOST: ${CFG_IRC_HOST:?}
      CFG_IRC_PORT: ${CFG_IRC_PORT:-6697}
      CFG_IRC_SSL: ${CFG_IRC_SSL:-true}
      CFG_LASTFM_API_KEY: ${CFG_LASTFM_API_KEY:-}
      CFG_NICKSERV_PASSWORD: ${CFG_NICKSERV_PASSWORD:-}
      CFG_SENTRY_DSN: ${CFG_SENTRY_DSN:-}
      PGID: ${PGID:?}
      PUID: ${PUID:?}
      TZ: ${TIMEZONE:-UTC}
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
