---
services:
  deluge:
    image: "ghcr.io/linuxserver/deluge:latest"
    container_name: "deluge"
    restart: "unless-stopped"
    environment:
      TZ: "${TZ:-UTC}"
      PGID: "${DELUGE_PGID:-${PGID:-1000}}"
      PUID: "${DELUGE_PUID:-${PUID:-1000}}"
      UMASK: "${UMASK:-007}"
    volumes:
      - "${BASE_DIR:-.}/config/deluge:/config"
      - "${BASE_DIR:-.}/data/torrents:/data/torrents"
    networks:
      - "mediaserver"
    ports:
      - "6882:6882"
      - "6882:6882/udp"
    deploy:
      resources:
        limits:
          cpus: "${DELUGE_CPU_LIMIT:-${CPU_LIMIT:-0}}"
          memory: "${DELUGE_MEM_LIMIT:-${MEM_LIMIT:-0}}"

  overseerr:
    image: "ghcr.io/linuxserver/overseerr:latest"
    container_name: "overseerr"
    restart: "unless-stopped"
    depends_on:
      - "plex"
      - "radarr"
      - "sonarr"
    environment:
      TZ: "${TZ:-UTC}"
      PGID: "${OVERSEERR_PGID:-${PGID:-1000}}"
      PUID: "${OVERSEERR_PUID:-${PUID:-1000}}"
      UMASK: "${UMASK:-007}"
    volumes:
      - "${BASE_DIR:-.}/config/overseerr:/config"
    networks:
      - "mediaserver"
    deploy:
      resources:
        limits:
          cpus: "${OVERSEERR_CPU_LIMIT:-${CPU_LIMIT:-0}}"
          memory: "${OVERSEERR_MEM_LIMIT:-${MEM_LIMIT:-0}}"

  plex:
    image: "ghcr.io/linuxserver/plex:latest"
    container_name: "plex"
    restart: "unless-stopped"
    environment:
      TZ: "${TZ:-UTC}"
      PGID: "${PLEX_PGID:-${PGID:-1000}}"
      PUID: "${PLEX_PUID:-${PUID:-1000}}"
      UMASK: "${UMASK:-007}"
      VERSION: "docker"
    env_file: ".env"
    volumes:
      - "${BASE_DIR:-.}/config/plex:/config"
      - "${BASE_DIR:-.}/data/media:/media:ro"
    tmpfs:
      - "/transcode:uid=${PLEX_PUID:-${PUID:-1000}},gid=${PLEX_PGID:-${PGID:-1000}},size=${PLEX_TRANSCODE_TMPFS_SIZE:-2G}"
    networks:
      - "mediaserver"
    deploy:
      resources:
        limits:
          cpus: "${PLEX_CPU_LIMIT:-${CPU_LIMIT:-0}}"
          memory: "${PLEX_MEM_LIMIT:-${MEM_LIMIT:-0}}"

  prowlarr:
    image: "ghcr.io/linuxserver/prowlarr:latest"
    container_name: "prowlarr"
    restart: "unless-stopped"
    environment:
      TZ: "${TZ:-UTC}"
      PGID: "${PROWLARR_PGID:-${PGID:-1000}}"
      PUID: "${PROWLARR_PUID:-${PUID:-1000}}"
      UMASK: "${UMASK:-007}"
    volumes:
      - "${BASE_DIR:-.}/config/prowlarr:/config"
    networks:
      - "mediaserver"
    deploy:
      resources:
        limits:
          cpus: "${PROWLARR_CPU_LIMIT:-${CPU_LIMIT:-0}}"
          memory: "${PROWLARR_MEM_LIMIT:-${MEM_LIMIT:-0}}"

  radarr:
    image: "ghcr.io/linuxserver/radarr:latest"
    container_name: "radarr"
    restart: "unless-stopped"
    depends_on:
      - "deluge"
      - "prowlarr"
    environment:
      TZ: "${TZ:-UTC}"
      PGID: "${RADARR_PGID:-${PGID:-1000}}"
      PUID: "${RADARR_PUID:-${PUID:-1000}}"
      UMASK: "${UMASK:-007}"
    volumes:
      - "${BASE_DIR:-.}/config/radarr:/config"
      - "${BASE_DIR:-.}/data:/data"
    networks:
      - "mediaserver"
    deploy:
      resources:
        limits:
          cpus: "${RADARR_CPU_LIMIT:-${CPU_LIMIT:-0}}"
          memory: "${RADARR_MEM_LIMIT:-${MEM_LIMIT:-0}}"

  sonarr:
    image: "ghcr.io/linuxserver/sonarr:latest"
    container_name: "sonarr"
    restart: "unless-stopped"
    depends_on:
      - "deluge"
      - "prowlarr"
    environment:
      TZ: "${TZ:-UTC}"
      PGID: "${SONARR_PGID:-${PGID:-1000}}"
      PUID: "${SONARR_PUID:-${PUID:-1000}}"
      UMASK: "${UMASK:-007}"
    volumes:
      - "${BASE_DIR:-.}/config/sonarr:/config"
      - "${BASE_DIR:-.}/data:/data"
    networks:
      - "mediaserver"
    deploy:
      resources:
        limits:
          cpus: "${SONARR_CPU_LIMIT:-${CPU_LIMIT:-0}}"
          memory: "${SONARR_MEM_LIMIT:-${MEM_LIMIT:-0}}"

  tautulli:
    image: "ghcr.io/linuxserver/tautulli:latest"
    container_name: "tautulli"
    restart: "unless-stopped"
    depends_on:
      - "plex"
    environment:
      TZ: "${TZ:-UTC}"
      PGID: "${TAUTULLI_PGID:-${PGID:-1000}}"
      PUID: "${TAUTULLI_PUID:-${PUID:-1000}}"
      UMASK: "${UMASK:-007}"
    volumes:
      - "${BASE_DIR:-.}/config/tautulli:/config"
      - "${BASE_DIR:-.}/config/plex/Library/Application Support/Plex Media Server/Logs:/plex_logs:ro"
    networks:
      - "mediaserver"
    deploy:
      resources:
        limits:
          cpus: "${TAUTULLI_CPU_LIMIT:-${CPU_LIMIT:-0}}"
          memory: "${TAUTULLI_MEM_LIMIT:-${MEM_LIMIT:-0}}"

networks:
  mediaserver:
    name: "mediaserver"
