version: '3.9'

services:
  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    volumes:
      - ${BASE_DIR:?}/config/deluge:/config
      - ${BASE_DIR:?}/data/torrents/incomplete:/downloads
      - ${BASE_DIR:?}/data/torrents:/data/torrents
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 127.0.0.1:8112:8112
      - 6882:6882
      - 6882:6882/udp
    labels:
      - diun.enable=true
    environment:
      PGID: ${PGID:?}
      PUID: ${PUID_DELUGE:?}
      TZ: ${TIMEZONE:-UTC}
      UMASK: ${UMASK:-007}
    restart: unless-stopped

  lidarr:
    image: hotio/lidarr:latest
    container_name: lidarr
    volumes:
      - ${BASE_DIR:?}/config/lidarr:/config
      - ${BASE_DIR:?}/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 127.0.0.1:8686:8686
    labels:
      - diun.enable=true
    environment:
      PGID: ${PGID:?}
      PUID: ${PUID_LIDARR:?}
      TZ: ${TIMEZONE:-UTC}
      UMASK: ${UMASK:-007}
    depends_on:
      - deluge
      - prowlarr
    restart: unless-stopped

  overseerr:
    image: hotio/overseerr:release
    container_name: overseerr
    volumes:
      - ${BASE_DIR:?}/config/overseerr:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 127.0.0.1:5055:5055
    labels:
      - diun.enable=true
    environment:
      PGID: ${PGID:?}
      PUID: ${PUID_OVERSEERR:?}
      TZ: ${TIMEZONE:-UTC}
      UMASK: ${UMASK:-007}
    depends_on:
      - plex
      - radarr
      - sonarr
    restart: unless-stopped

  plex:
    image: hotio/plex:release
    container_name: plex
    volumes:
      - ${BASE_DIR:?}/config/plex:/config
      - ${BASE_DIR:?}/data/media/transcode:/transcode
      - ${BASE_DIR:?}/data/media:/media
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 127.0.0.1:32400:32400
    deploy:
      resources:
        limits:
          cpus: ${PLEX_LIMIT_CPUS:-0}
          memory: ${PLEX_LIMIT_MEM:-0}
    labels:
      - diun.enable=true
    environment:
      PGID: ${PGID:?}
      PLEX_CLAIM:
      PLEX_PASS:
      ADVERTISE_IP:
      PUID: ${PUID_PLEX:?}
      TZ: ${TIMEZONE:-UTC}
      UMASK: ${UMASK:-007}
      VERSION: docker
    restart: unless-stopped

  prowlarr:
    image: hotio/prowlarr:nightly
    container_name: prowlarr
    volumes:
      - ${BASE_DIR:?}/config/prowlarr:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 127.0.0.1:9696:9696
    environment:
      PGID: ${PGID:?}
      PUID: ${PUID_PROWLARR:?}
      TZ: ${TIMEZONE:-UTC}
      UMASK: ${UMASK:-007}
    restart: unless-stopped

  radarr:
    image: hotio/radarr:latest
    container_name: radarr
    volumes:
      - ${BASE_DIR:?}/config/radarr:/config
      - ${BASE_DIR:?}/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 127.0.0.1:7878:7878
    labels:
      - diun.enable=true
    environment:
      PGID: ${PGID:?}
      PUID: ${PUID_RADARR:?}
      TZ: ${TIMEZONE:-UTC}
      UMASK: ${UMASK:-007}
    depends_on:
      - deluge
      - prowlarr
    restart: unless-stopped

  sonarr:
    image: hotio/sonarr:latest
    container_name: sonarr
    volumes:
      - ${BASE_DIR:?}/config/sonarr:/config
      - ${BASE_DIR:?}/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 127.0.0.1:8989:8989
    labels:
      - diun.enable=true
    environment:
      PGID: ${PGID:?}
      PUID: ${PUID_SONARR:?}
      TZ: ${TIMEZONE:-UTC}
      UMASK: ${UMASK:-007}
    depends_on:
      - deluge
      - prowlarr
    restart: unless-stopped
