version: '3.9'

services:
  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/config/deluge:/config
      - ${BASE_DIR:?}/data/torrents/incomplete:/downloads
      - ${BASE_DIR:?}/data/torrents:/data/torrents
    ports:
      - 6882:6882
      - 6882:6882/udp
    networks:
      - mediaserver
      - caddy
    labels:
      - diun.enable=true
    environment:
      PGID: ${PGID:?}
      PUID: ${PUID_DELUGE:?}
      UMASK: ${UMASK:-007}
    restart: unless-stopped

  lidarr:
    image: hotio/lidarr:latest
    container_name: lidarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/config/lidarr:/config
      - ${BASE_DIR:?}/data:/data
    networks:
      - mediaserver
      - caddy
    labels:
      - diun.enable=true
    environment:
      PGID: ${PGID:?}
      PUID: ${PUID_LIDARR:?}
      UMASK: ${UMASK:-007}
    depends_on:
      - deluge
      - prowlarr
    restart: unless-stopped

  overseerr:
    image: hotio/overseerr:release
    container_name: overseerr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/config/overseerr:/config
    networks:
      - mediaserver
      - caddy
    labels:
      - diun.enable=true
    environment:
      PGID: ${PGID:?}
      PUID: ${PUID_OVERSEERR:?}
      UMASK: ${UMASK:-007}
    depends_on:
      - plex
      - radarr
      - sonarr
    restart: unless-stopped

  plex:
    image: hotio/plex:release
    container_name: plex
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/config/plex:/config
      - ${BASE_DIR:?}/data/media/transcode:/transcode
      - ${BASE_DIR:?}/data/media:/media
    networks:
      - mediaserver
      - caddy
    deploy:
      resources:
        limits:
          cpus: ${PLEX_LIMIT_CPUS:-0}
          memory: ${PLEX_LIMIT_MEM:-0}
    labels:
      - diun.enable=true
    environment:
      PGID: ${PGID:?}
      PLEX_CLAIM:
      PLEX_PASS:
      ADVERTISE_IP:
      PUID: ${PUID_PLEX:?}
      UMASK: ${UMASK:-007}
      VERSION: docker
    restart: unless-stopped

  prowlarr:
    image: hotio/prowlarr:nightly
    container_name: prowlarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/config/prowlarr:/config
    networks:
      - mediaserver
      - caddy
    environment:
      PGID: ${PGID:?}
      PUID: ${PUID_PROWLARR:?}
      UMASK: ${UMASK:-007}
    restart: unless-stopped

  radarr:
    image: hotio/radarr:latest
    container_name: radarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/config/radarr:/config
      - ${BASE_DIR:?}/data:/data
    networks:
      - mediaserver
      - caddy
    labels:
      - diun.enable=true
    environment:
      PGID: ${PGID:?}
      PUID: ${PUID_RADARR:?}
      UMASK: ${UMASK:-007}
    depends_on:
      - deluge
      - prowlarr
    restart: unless-stopped

  sonarr:
    image: hotio/sonarr:latest
    container_name: sonarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/config/sonarr:/config
      - ${BASE_DIR:?}/data:/data
    networks:
      - mediaserver
      - caddy
    labels:
      - diun.enable=true
    environment:
      PGID: ${PGID:?}
      PUID: ${PUID_SONARR:?}
      UMASK: ${UMASK:-007}
    depends_on:
      - deluge
      - prowlarr
    restart: unless-stopped

networks:
  mediaserver:
    name: mediaserver
  caddy:
    external: true
