version: "3.9"

services:
  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    restart: unless-stopped
    environment:
      PGID: ${PGID:-1000}
      PUID: ${PUID_DELUGE:-1000}
      UMASK: ${UMASK:-007}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/config/deluge:/config
      - ${BASE_DIR:?}/data/torrents/incomplete:/downloads
      - ${BASE_DIR:?}/data/torrents:/data/torrents
    networks:
      - mediaserver
      - caddy
    ports:
      - 6882:6882
      - 6882:6882/udp
      - ${DELUGE_REMOTE_HOST:?}:${DELUGE_REMOTE_PORT:-58846}:58846

  lidarr:
    image: ghcr.io/hotio/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    depends_on:
      - deluge
      - prowlarr
    environment:
      PGID: ${PGID:-1000}
      PUID: ${PUID_LIDARR:-1000}
      UMASK: ${UMASK:-007}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/config/lidarr:/config
      - ${BASE_DIR:?}/data:/data
    networks:
      - mediaserver
      - caddy

  overseerr:
    image: ghcr.io/hotio/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    depends_on:
      - plex
      - radarr
      - sonarr
    environment:
      PGID: ${PGID:-1000}
      PUID: ${PUID_OVERSEERR:-1000}
      UMASK: ${UMASK:-007}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/config/overseerr:/config
    networks:
      - mediaserver
      - caddy

  plex:
    image: ghcr.io/hotio/plex:latest
    container_name: plex
    restart: unless-stopped
    environment:
      PGID: ${PGID:-1000}
      PLEX_CLAIM:
      PLEX_PASS:
      ADVERTISE_IP:
      PUID: ${PUID_PLEX:-1000}
      UMASK: ${UMASK:-007}
      VERSION: docker
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/config/plex:/config
      - ${BASE_DIR:?}/data/media/transcode:/transcode
      - ${BASE_DIR:?}/data/media:/media
    networks:
      - mediaserver
      - caddy
    deploy:
      resources:
        limits:
          cpus: ${PLEX_LIMIT_CPUS:-0}
          memory: ${PLEX_LIMIT_MEM:-0}

  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      PGID: ${PGID:-1000}
      PUID: ${PUID_PROWLARR:-1000}
      UMASK: ${UMASK:-007}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/config/prowlarr:/config
    networks:
      - mediaserver
      - caddy

  radarr:
    image: ghcr.io/hotio/radarr:latest
    container_name: radarr
    restart: unless-stopped
    depends_on:
      - deluge
      - prowlarr
    environment:
      PGID: ${PGID:-1000}
      PUID: ${PUID_RADARR:-1000}
      UMASK: ${UMASK:-007}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/config/radarr:/config
      - ${BASE_DIR:?}/data:/data
    networks:
      - mediaserver
      - caddy

  sonarr:
    image: ghcr.io/hotio/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    depends_on:
      - deluge
      - prowlarr
    environment:
      PGID: ${PGID:-1000}
      PUID: ${PUID_SONARR:-1000}
      UMASK: ${UMASK:-007}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/config/sonarr:/config
      - ${BASE_DIR:?}/data:/data
    networks:
      - mediaserver
      - caddy

networks:
  mediaserver:
    name: mediaserver
  caddy:
    external: true
