[project]
name = "stacks"
version = "0.1.0"
description = "Some docker-compose stacks 🤷"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pre-commit-hooks>=5.0.0",
    "yamllint>=1.37.1",
]
