---
services:
  caddy:
    image: "caddy-cloudflare:latest"
    container_name: "caddy"
    restart: "unless-stopped"
    init: true
    user: "${CADDY_PUID:-${PUID:-1000}}:${CADDY_PGID:-${PGID:-1000}}"
    build: "."
    pull_policy: "build"
    read_only: true
    env_file:
      - path: ".env"
        required: false
      - path: "stack.env"
        required: false
    environment:
      TZ: "${TZ:-UTC}"
      CF_API_TOKEN: "${CF_API_TOKEN:-}"
    volumes:
      - "${BASE_DIR:-.}/data:/data"
      - "${BASE_DIR:-.}/data/config:/config"
      - "${BASE_DIR:-.}/config:/etc/caddy"
    networks:
      - "caddy"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    deploy:
      resources:
        limits:
          cpus: "${CADDY_CPU_LIMIT:-${CPU_LIMIT:-0}}"
          memory: "${CADDY_MEM_LIMIT:-${MEM_LIMIT:-0}}"

networks:
  caddy:
    name: "caddy"
    enable_ipv6: true
    ipam:
      config:
        - subnet: "fd00:cafe:babe:1234::/64"
