services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    init: true
    user: ${PUID:-1000}:${PGID:-1000}
    read_only: true
    env_file: .env
    environment:
      CF_API_TOKEN: ${CF_API_TOKEN:-}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/data:/data
      - ${BASE_DIR:?}/config:/etc/caddy
      - caddy_config:/config
      - /srv/www:/srv/www:ro
      - /srv/pste/data/pste:/srv/pste/data:ro
      - /srv/rehome/data/rehome:/srv/rehome/data:ro
      - /srv/mediaserver/data/media:/srv/mediaserver/data/media:ro
    networks:
      - caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    extra_hosts:
      - host.docker.internal:host-gateway
    build: .
    deploy:
      resources:
        limits:
          cpus: ${CADDY_CPU_LIMIT:-${CPU_LIMIT:-0}}
          memory: ${CADDY_MEM_LIMIT:-${MEM_LIMIT:-0}}

networks:
  caddy:
    name: caddy
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:cafe:babe:1234::/64

volumes:
  caddy_config:
