version: "3.9"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    user: ${PUID:?}:${PGID:?}
    env_file: .env
    read_only: true
    environment:
      CF_API_TOKEN: ${CF_API_TOKEN:-}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/data:/data
      - ${BASE_DIR:?}/config:/etc/caddy:ro
      - caddy_config:/config
      - /srv/www:/srv/www:ro
      - /srv/pste/data:/srv/pste/data:ro
      - /srv/pste/static:/srv/pste/static:ro
      - /srv/rehome/data:/srv/rehome/data:ro
      - /srv/rehome/static:/srv/rehome/static:ro
      - /srv/gitea/public:/srv/gitea/public:ro
      - /srv/mediaserver/data/media:/srv/mediaserver/data/media:ro
      - /run/php-fpm:/run/php-fpm:ro
    networks:
      - caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    extra_hosts:
      - host.docker.internal:host-gateway
    build: .

networks:
  caddy:
    name: caddy
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:cafe:babe:1234::/64

volumes:
  caddy_config:
