version: '3.9'

services:
  gentoogram-bot:
    image: ghcr.io/thereverend403/gentoogram-bot:main
    container_name: gentoogram-bot
    restart: unless-stopped
    read_only: true
    user: ${PUID:?}:${PGID:?}
    environment:
      DYNACONF_SENTRY__DSN: ${SENTRY_DSN:-}
      DYNACONF_TELEGRAM__ADMIN_ID: ${TELEGRAM_ADMIN_ID:?}
      DYNACONF_TELEGRAM__CHAT_ID: ${TELEGRAM_CHAT_ID:?}
      DYNACONF_TELEGRAM__TOKEN: ${TELEGRAM_API_KEY:?}
      DYNACONF_TELEGRAM__WEBHOOK__ENABLED: ${TELEGRAM_WEBHOOK}
      DYNACONF_TELEGRAM__WEBHOOK__LISTEN: ${TELEGRAM_WEBHOOK_LISTEN}
      DYNACONF_TELEGRAM__WEBHOOK__PORT: ${TELEGRAM_WEBHOOK_PORT}
      DYNACONF_TELEGRAM__WEBHOOK__URL_BASE: ${TELEGRAM_WEBHOOK_URL_BASE}
      DYNACONF_TELEGRAM__WEBHOOK__URL_PATH: ${TELEGRAM_WEBHOOK_URL_PATH}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/config:/config
    networks:
      - gentoogram-bot
      - caddy
    labels:
      - telegram-notifier.monitor=true

networks:
  gentoogram-bot:
    name: gentoogram-bot
  caddy:
    external: true
