version: '3.9'

services:
  gentoogram-bot:
    image: ghcr.io/thereverend403/gentoogram-bot:main
    container_name: gentoogram-bot
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/config:/config
    tmpfs: /run:exec
    read_only: true
    networks:
      - gentoogram-bot
    labels:
      - telegram-notifier.monitor=true
    environment:
      DYNACONF_SENTRY__DSN: ${SENTRY_DSN:-}
      DYNACONF_TELEGRAM__ADMIN_ID: ${TELEGRAM_ADMIN_ID:?}
      DYNACONF_TELEGRAM__CHAT_ID: ${TELEGRAM_CHAT_ID:?}
      DYNACONF_TELEGRAM__TOKEN: ${TELEGRAM_API_KEY:?}
      PGID: ${PGID:?}
      PUID: ${PUID:?}
    restart: unless-stopped

networks:
  gentoogram-bot:
    name: gentoogram-bot
