---
services:
  uptime-kuma:
    image: "louislam/uptime-kuma:latest"
    container_name: "uptime-kuma"
    restart: "unless-stopped"
    env_file:
      - path: ".env"
        required: false
      - path: "stack.env"
        required: false
    environment:
      TZ: "${TZ:-UTC}"
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
    volumes:
      - "${BASE_DIR:-.}/data:/app/data"
    networks:
      - "uptime-kuma"
      - "caddy"
    deploy:
      resources:
        limits:
          cpus: "${CPU_LIMIT:-0}"
          memory: "${MEM_LIMIT:-0}"

networks:
  uptime-kuma:
    name: "uptime-kuma"
  caddy:
    external: true
