---
services:
  vaultwarden:
    image: "vaultwarden/server:latest"
    container_name: "vaultwarden"
    restart: "unless-stopped"
    init: true
    read_only: true
    user: "${VAULTWARDEN_PUID:-${PUID:-1000}}:${VAULTWARDEN_PGID:-${PGID:-1000}}"
    env_file: ".env"
    environment:
      TZ: "UTC"
      DATABASE_URL: "${DATABASE_URL:-postgresql://${POSTGRES_USER:-vaultwarden}:${POSTGRES_PASSWORD:-vaultwarden}@/${POSTGRES_DB:-vaultwarden}?host=${POSTGRES_HOST:-/run/postgresql}}"
      ADMIN_TOKEN: "${ADMIN_TOKEN:?}"
    volumes:
      - "${BASE_DIR:-.}/data/vaultwarden:/data"
    networks:
      - "vaultwarden"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "${VAULTWARDEN_CPU_LIMIT:-${CPU_LIMIT:-0}}"
          memory: "${VAULTWARDEN_MEM_LIMIT:-${MEM_LIMIT:-0}}"
    healthcheck:
      test:
        - "CMD"
        - "/healthcheck.sh"
      start_period: "10s"
      start_interval: "1s"
      interval: "10s"
      timeout: "5s"

networks:
  vaultwarden:
    name: "vaultwarden"
