---
services:
  vaultwarden:
    image: "vaultwarden/server:latest"
    container_name: "vaultwarden"
    restart: "no"
    init: true
    read_only: true
    user: "${VAULTWARDEN_PUID:-${PUID:-1000}}:${VAULTWARDEN_PGID:-${PGID:-1000}}"
    env_file: ".env"
    depends_on:
      db-17:
        condition: "service_healthy"
    environment:
      TZ: "UTC"
      DATABASE_URL: "postgresql://${POSTGRES_USER:-vaultwarden}:${POSTGRES_PASSWORD:-vaultwarden}@/${POSTGRES_DB:-vaultwarden}?host=${POSTGRES_HOST:-/run/postgresql}"
      LOG_LEVEL: "info"
      EXTENDED_LOGGING: false
    volumes:
      - "postgres_17_socket:/run/postgresql"
      - "${BASE_DIR:-.}/data/vaultwarden:/data"
    networks:
      - "vaultwarden"
      - "caddy"
    deploy:
      resources:
        limits:
          cpus: "${VAULTWARDEN_CPU_LIMIT:-${CPU_LIMIT:-0}}"
          memory: "${VAULTWARDEN_MEM_LIMIT:-${MEM_LIMIT:-0}}"

  db-17:
    image: "postgres:17-alpine"
    container_name: "vaultwarden_db_17"
    restart: "unless-stopped"
    init: true
    user: "${POSTGRES_PUID:-${PUID:-1000}}:${POSTGRES_PGID:-${PGID:-1000}}"
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    network_mode: "none"
    environment:
      TZ: "UTC"
      POSTGRES_HOST: "/run/postgresql"
      POSTGRES_DB: "vaultwarden"
      POSTGRES_USER: "vaultwarden"
      POSTGRES_PASSWORD: "vaultwarden"
    volumes:
      - "${BASE_DIR:-.}/data/db/17:/var/lib/postgresql/data"
      - "${BASE_DIR:-.}/config/db/17:/etc/postgresql"
      - "postgres_17_socket:/run/postgresql"
    tmpfs:
      - "/run"
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -q --dbname=$$POSTGRES_DB --username=$$POSTGRES_USER --host=$$POSTGRES_HOST"
      start_period: "10s"
      start_interval: "1s"
      interval: "10s"
      timeout: "5s"
    shm_size: "${SHM_SIZE:-512M}"
    deploy:
      resources:
        limits:
          cpus: "${POSTGRES_CPU_LIMIT:-${CPU_LIMIT:-0}}"
          memory: "${POSTGRES_MEM_LIMIT:-${MEM_LIMIT:-0}}"

volumes:
  postgres_17_socket:

networks:
  vaultwarden:
    name: "vaultwarden"
  caddy:
    external: true
