version: "3.9"

services:
  pste:
    image: ghcr.io/thereverend403/pste:latest
    container_name: pste
    restart: unless-stopped
    tmpfs:
      - /tmp
      - /run:exec
    environment:
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY:?}
      FLASK_SENTRY_DSN: ${FLASK_SENTRY_DSN:-}
      FLASK_SQLALCHEMY_DATABASE_URI: ${FLASK_SQLALCHEMY_DATABASE_URI:?}
      GUNICORN_OPTS: ${GUNICORN_OPTS:-}
      PUID: ${PUID:?}
      PGID: ${PGID:?}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/postgresql:/run/postgresql
      - ${BASE_DIR:?}/config:/config
      - ${BASE_DIR:?}/data:/data
      - ${BASE_DIR:?}/static:/static
    networks:
      - pste
      - caddy

networks:
  pste:
    name: pste
  caddy:
    external: true
