version: "3.9"

services:
  pste:
    image: ghcr.io/thereverend403/pste:main
    container_name: pste
    restart: unless-stopped
    env_file: .env
    environment:
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY:?}
      FLASK_SENTRY_DSN: ${FLASK_SENTRY_DSN:-}
      FLASK_SQLALCHEMY_DATABASE_URI: ${FLASK_SQLALCHEMY_DATABASE_URI:?}
      GUNICORN_OPTS: ${GUNICORN_OPTS:-}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/postgresql:/run/postgresql
      - ${BASE_DIR:?}/config:/config
      - ${BASE_DIR:?}/data:/data
      - ${BASE_DIR:?}/static:/static
    tmpfs:
      - /tmp
      - /run:exec
    networks:
      - pste
      - caddy
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT:-0}
          memory: ${MEM_LIMIT:-0}

networks:
  pste:
    name: pste
  caddy:
    external: true
