version: "3.9"

services:
  pste:
    image: ghcr.io/thereverend403/pste:main
    container_name: pste
    restart: unless-stopped
    init: true
    read_only: true
    user: ${PUID:-1000}:${PGID:-1000}
    depends_on:
      keydb:
        condition: service_healthy
    env_file: .env
    environment:
      CFG_SECRET_KEY: ${CFG_SECRET_KEY:?}
      CFG_SQLALCHEMY_DATABASE_URI: ${CFG_SQLALCHEMY_DATABASE_URI:?}
      CFG_KEYDB_URL: ${CFG_REDIS_URL:-redis://keydb:6379}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/postgresql:/run/postgresql
      - ${BASE_DIR:?}/config:/config
      - ${BASE_DIR:?}/data:/data
    tmpfs:
      - /tmp
    networks:
      - pste
      - caddy
    labels:
      - diun.regopt=ghcr
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT:-0}
          memory: ${MEM_LIMIT:-0}

  keydb:
    image: eqalpha/keydb:latest
    container_name: pste_keydb
    command:
      - --dir /data
      - --dbfilename dump.rdb
      - --save 60 10
      - --appendonly yes
      - --appendfilename appendonly.aof
      - ${KEYDB_ARGS:-}
    restart: unless-stopped
    init: true
    user: ${PUID:-1000}:${PGID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/keydb/data:/data
    networks:
      - pste
    healthcheck:
      test: ["CMD-SHELL", "keydb-cli ping | grep PONG"]
      start_period: 10s
      start_interval: 1s
      interval: 10s
      timeout: 5s
    deploy:
      resources:
        limits:
          cpus: ${KEYDB_CPU_LIMIT:-${CPU_LIMIT:-0}}
          memory: ${KEYDB_MEM_LIMIT:-${MEM_LIMIT:-0}}

networks:
  pste:
    name: pste
  caddy:
    external: true
