---
services:
  diun:
    image: "crazymax/diun:latest"
    container_name: "diun"
    command: "serve"
    restart: "unless-stopped"
    init: true
    env_file:
      - path: ".env"
        required: false
      - path: "stack.env"
        required: false
    environment:
      TZ: "${TZ:-UTC}"
      DIUN_PROVIDERS_DOCKER: "${DIUN_PROVIDERS_DOCKER:-true}"
      DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT: "${DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT:-true}"
      DIUN_WATCH_SCHEDULE: "${DIUN_WATCH_SCHEDULE:-0 */6 * * *}"
      DIUN_WATCH_WORKERS: "${DIUN_WATCH_WORKERS:-4}"
      LOG_JSON: "${LOG_JSON:-false}"
      LOG_LEVEL: "${LOG_LEVEL:-info}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${BASE_DIR:-.}/data/diun:/data"
      - "${BASE_DIR:-.}/config/diun:/etc/diun"
    networks:
      - "docker-monitoring"
    deploy:
      resources:
        limits:
          cpus: "${DIUN_CPU_LIMIT:-${CPU_LIMIT:-0}}"
          memory: "${DIUN_MEM_LIMIT:-${MEM_LIMIT:-0}}"

networks:
  docker-monitoring:
    name: "docker-monitoring"
