version: '3.9'

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    env_file:
      - ../stack.env
    environment:
      USER_UID: ${PUID:-1000}
      USER_GID: ${PGID:-1000}
      GITEA_CUSTOM: /data/gitea/custom
      GITEA__database__DB_TYPE: ${DB_TYPE:-postgres}
      GITEA__database__HOST: ${DB_HOST:?}
      GITEA__database__NAME: ${DB_NAME:?}
      GITEA__database__USER: ${DB_USER:?}
      GITEA__database__PASSWD: ${DB_PASSWORD:?}
      GITEA__server__HTTP_PORT: ${GITEA_HTTP_PORT:-3000}
    ports:
      - "127.0.0.1:${GITEA_HTTP_PORT:-3000}:${GITEA_HTTP_PORT:-3000}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /run/postgresql:/run/postgresql
      - ${BASE_DIR:?}/data:/data
      - ${BASE_DIR:?}/git:/data/git
      - ${BASE_DIR:?}/logs:/data/gitea/log
      - ${BASE_DIR:?}/custom:/data/gitea/custom
      - ${BASE_DIR:?}/config:/data/gitea/conf
    labels:
      - diun.enable=true
      - telegram-notifier.monitor=true
    restart: unless-stopped
