version: '3.9'

services:
  # Fix redis /tmp and /data perms so it can actually write to them.
  gitea_redis_chown:
    image: busybox:latest
    command: chown -R ${PUID:?}:${PGID:?} /tmp/redis /data
    restart: no
    volumes:
        - redis_socket:/tmp/redis

  redis:
    image: redis:alpine
    container_name: gitea_redis
    command: ${REDIS_ARGS:-/usr/local/etc/redis/redis.conf}
    restart: unless-stopped
    user: ${PUID:?}:${PGID:?}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - redis_socket:/tmp/redis
      - ${BASE_DIR:?}/redis/data:/data
      - ${BASE_DIR:?}/redis/config:/usr/local/etc/redis
    networks:
      - gitea
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -s /tmp/redis/redis.sock ping | grep PONG"]
      start_period: 5s
      interval: 5s
      retries: 5
      timeout: 3s
    labels:
      - diun.enable=true
      - telegram-notifier.monitor=true

  gitea:
    image: gitea/gitea:latest-rootless
    container_name: gitea
    restart: unless-stopped
    tmpfs: /tmp
    user: ${PUID:?}:${PGID:?}
    depends_on:
      - redis
    env_file:
      - ../stack.env
    environment:
      USER_UID: ${PUID:?}
      USER_GID: ${PGID:?}
      GITEA__database__DB_TYPE: ${DB_TYPE:-postgres}
      GITEA__database__HOST: ${DB_HOST:-/run/postgresql}
      GITEA__database__NAME: ${DB_NAME:-gitea}
      GITEA__database__USER: ${DB_USER:-gitea}
      GITEA__database__PASSWD: ${DB_PASSWD:?}
      GITEA__server__HTTP_PORT: ${HTTP_PORT:-3000}
      GITEA__queue__TYPE: redis
      GITEA__queue__CONN_STR: ${REDIS_URL:-redis://gitea_redis:6379/0}
      "GITEA__queue.issue_indexer__TYPE": redis
      "GITEA__queue.issue_indexer__CONN_STR": ${REDIS_URL:-redis://gitea_redis:6379/0}
      GITEA__cache__ADAPTER: redis
      GITEA__cache__HOST: ${REDIS_URL:-redis://gitea_redis:6379/0}
      GITEA__session__PROVIDER: db
      GITEA__indexer__ISSUE_INDEXER_TYPE: db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /run/postgresql:/run/postgresql
      - redis_socket:/tmp/redis
      - ${BASE_DIR:?}/data:/var/lib/gitea
      - ${BASE_DIR:?}/git:/var/lib/gitea/git
      - ${BASE_DIR:?}/config:/etc/gitea
    networks:
      - gitea
      - caddy
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs gitea:${HTTP_PORT:-3000}/api/healthz"]
      start_period: 10s
      interval: 30s
      timeout: 5s
      retries: 5
    labels:
      - diun.enable=true
      - telegram-notifier.monitor=true

networks:
  gitea:
    name: gitea
  caddy:
    external: true

volumes:
  redis_socket:
