services:
  gitea:
    image: gitea/gitea:latest-rootless
    container_name: gitea
    restart: unless-stopped
    user: ${PUID:-1000}:${PGID:-1000}
    depends_on:
      redis:
        condition: service_healthy
    env_file: .env
    environment:
      USER_UID: ${PUID:-1000}
      USER_GID: ${PGID:-1000}
      GITEA__database__DB_TYPE: ${DB_TYPE:-postgres}
      GITEA__database__HOST: ${DB_HOST:-/run/postgresql}
      GITEA__database__NAME: ${DB_NAME:-gitea}
      GITEA__database__USER: ${DB_USER:-gitea}
      GITEA__database__PASSWD: ${DB_PASSWD:?}
      GITEA__server__HTTP_PORT: ${HTTP_PORT:-3000}
      GITEA__queue__TYPE: redis
      GITEA__queue__CONN_STR: ${GITEA__queue__CONN_STR:-${REDIS_URL:-redis://redis:6379/0}}
      GITEA__cache__ADAPTER: redis
      GITEA__cache__HOST: ${GITEA__cache__HOST:-${REDIS_URL:-redis://redis:6379/0}}
      GITEA__session__PROVIDER: redis
      GITEA__session__PROVIDER_CONFIG: ${GITEA__session__PROVIDER_CONFIG:-${REDIS_URL:-redis://redis:6379/0}}
      GITEA__indexer__ISSUE_INDEXER_TYPE: db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - postgres_17_socket:/run/postgresql
      - ${BASE_DIR:?}/data/gitea:/var/lib/gitea
      - ${BASE_DIR:?}/config/gitea:/etc/gitea
    tmpfs:
      - /tmp
    networks:
      - gitea
      - caddy
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs gitea:${HTTP_PORT:-3000}/api/healthz"]
      start_period: 10s
      start_interval: 1s
      interval: 10s
      timeout: 5s
    deploy:
      resources:
        limits:
          cpus: ${GITEA_CPU_LIMIT:-${CPU_LIMIT:-0}}
          memory: ${GITEA_MEM_LIMIT:-${MEM_LIMIT:-0}}

  db-17:
    image: postgres:17-alpine
    container_name: gitea_db_17
    restart: unless-stopped
    user: ${PUID:?}:${PGID:?}
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    network_mode: "none"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:-.}/data/db/17:/var/lib/postgresql/data
      - ${BASE_DIR:-.}/config/db/17/postgresql.conf:/etc/postgresql.conf
      - postgres_17_socket:/run/postgresql
    tmpfs:
      - /run
    environment:
      POSTGRES_HOST: ${DB_HOST:-/run/postgresql}
      POSTGRES_DB: ${DB_NAME:-gitea}
      POSTGRES_USER: ${DB_USER:-gitea}
      POSTGRES_PASSWORD: ${DB_PASSWD:?}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -q --username=$$POSTGRES_USER --host=$$POSTGRES_HOST",
        ]
      start_period: 5s
      interval: 10s
      timeout: 5s

  redis:
    image: redis:latest
    container_name: gitea_redis
    command:
      - --dir /data
      - --appendonly yes
      - ${REDIS_ARGS:-}
    restart: unless-stopped
    init: true
    user: ${PUID:-1000}:${PGID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/data/redis:/data
    networks:
      - gitea
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 10s
      start_interval: 1s
      interval: 10s
      timeout: 5s
    deploy:
      resources:
        limits:
          cpus: ${REDIS_CPU_LIMIT:-${CPU_LIMIT:-0}}
          memory: ${REDIS_MEM_LIMIT:-${MEM_LIMIT:-0}}

networks:
  gitea:
    name: gitea
  caddy:
    external: true
