version: "3.9"

services:
  redis_socket:
    image: busybox:latest
    container_name: gitea_redis_socket
    command: chmod -R 777 /run/redis
    volumes:
      - redis_socket:/run/redis

  redis:
    image: redis:alpine
    container_name: gitea_redis
    command: ${REDIS_ARGS:-} /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    user: ${PUID:-1000}:${PGID:-1000}
    depends_on:
      - redis_socket
    network_mode: "none"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - redis_socket:/run/redis
      - ${BASE_DIR:?}/redis/data:/data
      - ${BASE_DIR:?}/redis/config:/usr/local/etc/redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -s /run/redis/redis.sock ping | grep PONG"]
      start_period: 5s
      interval: 5s
      retries: 5
      timeout: 3s
    deploy:
      resources:
        limits:
          cpus: ${REDIS_CPU_LIMIT:-${CPU_LIMIT:-0}}
          memory: ${REDIS_MEM_LIMIT:-${MEM_LIMIT:-0}}

  gitea:
    image: gitea/gitea:latest-rootless
    container_name: gitea
    restart: unless-stopped
    tmpfs: /tmp
    user: ${PUID:-1000}:${PGID:-1000}
    depends_on:
      redis:
        condition: service_healthy
    env_file: .env
    environment:
      USER_UID: ${PUID:-1000}
      USER_GID: ${PGID:-1000}
      GITEA__database__DB_TYPE: ${DB_TYPE:-postgres}
      GITEA__database__HOST: ${DB_HOST:-/run/postgresql}
      GITEA__database__NAME: ${DB_NAME:-gitea}
      GITEA__database__USER: ${DB_USER:-gitea}
      GITEA__database__PASSWD: ${DB_PASSWD:?}
      GITEA__server__HTTP_PORT: ${HTTP_PORT:-3000}
      GITEA__queue__TYPE: redis
      GITEA__queue__CONN_STR: ${REDIS_URL:-network=unix,addr=/run/redis/redis.sock,db=0}
      "GITEA__queue.issue_indexer__TYPE": redis
      "GITEA__queue.issue_indexer__CONN_STR": ${REDIS_URL:-network=unix,addr=/run/redis/redis.sock,db=0}
      GITEA__cache__ADAPTER: redis
      GITEA__cache__HOST: ${REDIS_URL:-network=unix,addr=/run/redis/redis.sock,db=0}
      GITEA__session__PROVIDER: redis
      GITEA__session__PROVIDER_CONFIG: ${REDIS_URL:-network=unix,addr=/run/redis/redis.sock,db=0}
      GITEA__indexer__ISSUE_INDEXER_TYPE: db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /run/postgresql:/run/postgresql
      - redis_socket:/run/redis
      - ${BASE_DIR:?}/data:/var/lib/gitea
      - ${BASE_DIR:?}/config:/etc/gitea
    networks:
      - gitea
      - caddy
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs gitea:${HTTP_PORT:-3000}/api/healthz"]
      start_period: 10s
      interval: 30s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: ${GITEA_CPU_LIMIT:-${CPU_LIMIT:-0}}
          memory: ${GITEA_MEM_LIMIT:-${MEM_LIMIT:-0}}

networks:
  gitea:
    name: gitea
  caddy:
    external: true

volumes:
  redis_socket:
