version: "3.9"

services:
  gitea:
    image: gitea/gitea:latest-rootless
    container_name: gitea
    restart: unless-stopped
    user: ${PUID:-1000}:${PGID:-1000}
    depends_on:
      keydb:
        condition: service_healthy
    env_file: .env
    environment:
      USER_UID: ${PUID:-1000}
      USER_GID: ${PGID:-1000}
      GITEA__database__DB_TYPE: ${DB_TYPE:-postgres}
      GITEA__database__HOST: ${DB_HOST:-/run/postgresql}
      GITEA__database__NAME: ${DB_NAME:-gitea}
      GITEA__database__USER: ${DB_USER:-gitea}
      GITEA__database__PASSWD: ${DB_PASSWD:?}
      GITEA__server__HTTP_PORT: ${HTTP_PORT:-3000}
      GITEA__queue__TYPE: redis
      GITEA__queue__CONN_STR: ${GITEA__queue__CONN_STR:-${KEYDB_URL:-redis://keydb:6379/0}}
      GITEA__cache__ADAPTER: redis
      GITEA__cache__HOST: ${GITEA__cache__HOST:-${KEYDB_URL:-redis://keydb:6379/0}}
      GITEA__session__PROVIDER: redis
      GITEA__session__PROVIDER_CONFIG: ${GITEA__session__PROVIDER_CONFIG:-${KEYDB_URL:-redis://keydb:6379/0}}
      GITEA__indexer__ISSUE_INDEXER_TYPE: db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/postgresql:/run/postgresql
      - ${BASE_DIR:?}/data:/var/lib/gitea
      - ${BASE_DIR:?}/config:/etc/gitea
    tmpfs:
      - /tmp
    networks:
      - gitea
      - caddy
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs gitea:${HTTP_PORT:-3000}/api/healthz"]
      start_period: 10s
      start_interval: 1s
      interval: 10s
      timeout: 5s
    deploy:
      resources:
        limits:
          cpus: ${GITEA_CPU_LIMIT:-${CPU_LIMIT:-0}}
          memory: ${GITEA_MEM_LIMIT:-${MEM_LIMIT:-0}}

  keydb:
    image: eqalpha/keydb:latest
    container_name: gitea_keydb
    command:
      - --dir /data
      - --dbfilename dump.rdb
      - --save 60 1000
      - --save 600 100
      - --save 3600 10
      - --appendonly yes
      - --appendfilename appendonly.aof
      - ${KEYDB_ARGS:-}
    restart: unless-stopped
    init: true
    user: ${PUID:-1000}:${PGID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/keydb/data:/data
    networks:
      - gitea
    healthcheck:
      test: ["CMD-SHELL", "keydb-cli ping | grep PONG"]
      start_period: 10s
      start_interval: 1s
      interval: 10s
      timeout: 5s
    deploy:
      resources:
        limits:
          cpus: ${KEYDB_CPU_LIMIT:-${CPU_LIMIT:-0}}
          memory: ${KEYDB_MEM_LIMIT:-${MEM_LIMIT:-0}}

networks:
  gitea:
    name: gitea
  caddy:
    external: true
