version: '3.9'

services:
  redis:
    image: redis:alpine
    container_name: redis
    command: ${REDIS_ARGS:---save 60 1 --loglevel warning}
    user: ${PUID:-1000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 5s
      interval: 5s
      retries: 5
      timeout: 3s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${BASE_DIR:?}/redis:/data
    labels:
      - diun.enable=true
      - telegram-notifier.monitor=true

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    depends_on:
      - redis
    env_file:
      - ../stack.env
    environment:
      USER_UID: ${PUID:-1000}
      USER_GID: ${PGID:-1000}
      GITEA__database__DB_TYPE: ${DB_TYPE:-postgres}
      GITEA__database__HOST: ${DB_HOST:-/run/postgresql}
      GITEA__database__NAME: ${DB_NAME:-gitea}
      GITEA__database__USER: ${DB_USER:-gitea}
      GITEA__database__PASSWD: ${DB_PASSWORD:?}
      GITEA__server__HTTP_PORT: ${GITEA_HTTP_PORT:-3000}
      GITEA__queue__TYPE: redis
      GITEA__queue__CONN_STR: ${REDIS_URL:-redis://redis:6379/0}
      "GITEA__queue.issue_indexer__TYPE": redis
      "GITEA__queue.issue_indexer__CONN_STR": ${REDIS_URL:-redis://redis:6379/0}
      GITEA__cache__ADAPTER: redis
      GITEA__cache__HOST: ${REDIS_URL:-redis://redis:6379/0}
      GITEA__session__PROVIDER: db
      GITEA__indexer__ISSUE_INDEXER_TYPE: db
    ports:
      - "127.0.0.1:${GITEA_HTTP_PORT:-3000}:${GITEA_HTTP_PORT:-3000}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /run/postgresql:/run/postgresql
      - ${BASE_DIR:?}/data:/data
      - ${BASE_DIR:?}/git:/data/git
      - ${BASE_DIR:?}/logs:/data/gitea/log
      - ${BASE_DIR:?}/config:/data/gitea/conf
    labels:
      - diun.enable=true
      - telegram-notifier.monitor=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs gitea:${GITEA_HTTP_PORT:-3000}/api/healthz"]
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 5
