version: '3.9'

services:
  diun:
    image: crazymax/diun:latest
    command: serve
    container_name: diun
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    labels:
      - diun.enable=true
    environment:
      DIUN_NOTIF_TELEGRAM_CHATIDS: ${TELEGRAM_CHAT_ID:?}
      DIUN_NOTIF_TELEGRAM_TOKEN: ${TELEGRAM_API_KEY:?}
      DIUN_PROVIDERS_DOCKER: 'true'
      DIUN_WATCH_SCHEDULE: ${DIUN_WATCH_SCHEDULE:-0 */6 * * *}
      DIUN_WATCH_WORKERS: ${DIUN_WATCH_WORKERS:-4}
      LOG_JSON: 'false'
      LOG_LEVEL: info
    restart: always

  telegram-notifier:
    image: poma/docker-telegram-notifier:latest
    container_name: telegram-notifier
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - diun.enable=true
      - telegram-notifier.monitor=true
    environment:
      ONLY_WHITELIST: 'true'
      TELEGRAM_NOTIFIER_BOT_TOKEN: ${TELEGRAM_API_KEY:?}
      TELEGRAM_NOTIFIER_CHAT_ID: ${TELEGRAM_CHAT_ID:?}
    restart: always

volumes:
  data:
