---
services:
  portainer:
    image: "portainer/portainer-ee:alpine"
    container_name: "portainer"
    command: "-H unix:///var/run/docker.sock"
    restart: "unless-stopped"
    init: true
    user: "${PORTAINER_PUID:-${PUID:-1000}}:${PORTAINER_PGID:-${PGID:-1000}}"
    environment:
      TZ: "${TZ:-UTC}"
      UMASK: "${UMASK:-007}"
      VIRTUAL_HOST: "${VIRTUAL_HOST?}"
      VIRTUAL_PORT: "${VIRTUAL_PORT:-9000}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${BASE_DIR:-.}/data:/data"
    networks:
      - "portainer"
      - "caddy"
    deploy:
      resources:
        limits:
          cpus: "${PORTAINER_CPU_LIMIT:-${CPU_LIMIT:-0}}"
          memory: "${PORTAINER_MEM_LIMIT:-${MEM_LIMIT:-0}}"

networks:
  portainer:
    name: "portainer"
  caddy:
    external: true
