version: '3.9'

services:
  portainer:
    image: portainer/portainer-ee:alpine
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    environment:
      UMASK: ${UMASK:-007}
      VIRTUAL_HOST: ${HOST?}
      VIRTUAL_PORT: ${PORT:-9000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BASE_DIR:?}/data:/data
    networks:
      - portainer
      - caddy
    labels:
      - diun.enable=true
      - telegram-notifier.monitor=true

networks:
  portainer:
    name: portainer
  caddy:
    external: true
