---
services:
  proxy:
    image: "itzg/bungeecord:latest"
    container_name: "proxy"
    restart: "unless-stopped"
    user: "${PROXY_PUID:-${PUID:-1000}}:${PROXY_PGID:-${PGID:-1000}}"
    depends_on:
      survival:
        condition: "service_healthy"
    stdin_open: true
    tty: true
    env_file:
      - path: ".env"
        required: false
    environment:
      TZ: "UTC"
      ENABLE_RCON: "true"
      JVM_XX_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch"
      UID: "${PROXY_PUID:-${PUID:-1000}}"
      GID: "${PROXY_PGID:-${PGID:-1000}}"
      MEMORY: "${PROXY_MEM_LIMIT:-${MEM_LIMIT:-}}"
      REPLACE_ENV_VARIABLES: "true"
      TYPE: "${PROXY_TYPE:-WATERFALL}"
      PATCH_DEFINITIONS: "/config/patches"
    volumes:
      - "${BASE_DIR:-.}/config/proxy:/config"
      - "${BASE_DIR:-.}/data/proxy:/server"
    networks:
      - "minecraft"
    ports:
      - "25565:25577"
    deploy:
      resources:
        limits:
          cpus: "${PROXY_CPU_LIMIT:-${CPU_LIMIT:-0}}"
          memory: "${PROXY_MEM_LIMIT:-${MEM_LIMIT:-0}}"

  survival:
    image: "itzg/minecraft-server:latest"
    container_name: "survival"
    restart: "unless-stopped"
    user: "${SERVER_PUID:-${PUID:-1000}}:${SERVER_PGID:-${PGID:-1000}}"
    stdin_open: true
    tty: true
    env_file:
      - path: ".env"
        required: false
    environment:
      TZ: "UTC"
      ENABLE_ROLLING_LOGS: "true"
      EULA: "true"
      JVM_DD_OPTS: "${JVM_DD_OPTS:-paper.useLegacyPluginLoading=true}"
      UID: "${SERVER_PUID:-${PUID:-1000}}"
      GID: "${SERVER_PGID:-${PGID:-1000}}"
      MEMORY: "${SERVER_MEM_LIMIT:-${MEM_LIMIT:-}}"
      REPLACE_ENV_VARIABLES: "true"
      TYPE: "PAPER"
      USE_AIKAR_FLAGS: "true"
      VERSION: "${VERSION:-LATEST}"
      PATCH_DEFINITIONS: "/config/patches"
    volumes:
      - "${BASE_DIR:-.}/config/survival:/config"
      - "${BASE_DIR:-.}/data/survival:/data"
    networks:
      - "minecraft"
    deploy:
      resources:
        limits:
          cpus: "${SERVER_CPU_LIMIT:-${CPU_LIMIT:-0}}"
          memory: "${SERVER_MEM_LIMIT:-${MEM_LIMIT:-0}}"

  db:
    image: "mariadb:latest"
    container_name: "minecraft_db"
    restart: "unless-stopped"
    init: true
    user: "${MARIADB_PUID:-${PUID:-1000}}:${MARIADB_PGID:-${PGID:-1000}}"
    networks:
      - "minecraft"
    env_file:
      - path: ".env"
        required: false
    environment:
      TZ: "UTC"
      MARIADB_DATABASE: "minecraft"
      MARIADB_USER: "minecraft"
      MARIADB_PASSWORD: "minecraft"
      MARIADB_ROOT_PASSWORD: "minecraft"
    volumes:
      - "${BASE_DIR:-.}/data/db:/var/lib/mysql"
    deploy:
      resources:
        limits:
          cpus: "${MARIADB_CPU_LIMIT:-${CPU_LIMIT:-0}}"
          memory: "${MARIADB_MEM_LIMIT:-${MEM_LIMIT:-0}}"

networks:
  minecraft:
    name: "minecraft"
