version: '3.9'

services:
  proxy:
    image: itzg/bungeecord:latest
    container_name: proxy
    volumes:
      - ${BASE_DIR:?}/waterfall/config:/config
      - ${BASE_DIR:?}/waterfall/data:/server
      - ${BASE_DIR:?}/waterfall/logs:/server/logs
      - ${BASE_DIR:?}/waterfall/plugins:/plugins
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 25565:25577
    deploy:
      resources:
        limits:
          cpus: ${PROXY_LIMIT_CPUS:-0}
          memory: ${PROXY_LIMIT_MEM:-0}
    labels:
      - diun.enable=true
      - telegram-notifier.monitor=true
    environment:
      CFG_DB_PASSWORD: ${DB_PASSWORD:?}
      CFG_DB_USER: ${DB_USER:?}
      CFG_MYSQL_HOST: ${MYSQL_HOST:?}
      CFG_MYSQL_PORT: ${MYSQL_PORT:-3306}
      CFG_POSTGRES_HOST: ${POSTGRES_HOST:?}
      CFG_POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      ENABLE_RCON: 'true'
      GID: ${PGID:?}
      JVM_XX_OPTS: -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch
      MEMORY: ${PROXY_MEMORY:?}
      REPLACE_ENV_VARIABLES: 'true'
      TYPE: WATERFALL
      WATERFALL_VERSION: ${VERSION:-latest}
      TZ: ${TIMEZONE:-UTC}
      UID: ${PUID:?}
    stdin_open: true
    user: ${PUID:?}:${PGID:?}
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    tty: true

  survival:
    image: itzg/minecraft-server:latest
    container_name: survival
    volumes:
      - ${BASE_DIR:?}/survival/config:/config
      - ${BASE_DIR:?}/survival/data:/data
      - ${BASE_DIR:?}/survival/plugins:/plugins
      - ${BASE_DIR:?}/survival/worlds:/worlds
      - ${BASE_DIR:?}/survival/logs:/data/logs
      - ${MAP_DIR:?}:/map
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: ${SERVER_LIMIT_CPUS:-0}
          memory: ${SERVER_LIMIT_MEM:-0}
    labels:
      - diun.enable=true
      - telegram-notifier.monitor=true
    environment:
      CFG_DB_PASSWORD: ${DB_PASSWORD:?}
      CFG_DB_USER: ${DB_USER:?}
      CFG_DISCORD_TOKEN: ${DISCORD_TOKEN:?}
      CFG_MYSQL_HOST: ${MYSQL_HOST:?}
      CFG_MYSQL_PORT: ${MYSQL_PORT:-3306}
      CFG_POSTGRES_HOST: ${POSTGRES_HOST:?}
      CFG_POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      COPY_CONFIG_DEST: /data
      ENABLE_ROLLING_LOGS: 'true'
      EULA: 'true'
      GID: ${PGID:?}
      MEMORY: ${SERVER_MEMORY:?}
      REPLACE_ENV_VARIABLES: 'true'
      TYPE: PAPER
      TZ: ${TIMEZONE:-UTC}
      UID: ${PUID:?}
      USE_AIKAR_FLAGS: 'true'
      VERSION: ${VERSION:-LATEST}
    stdin_open: true
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    tty: true
