version: "3.9"

services:
  proxy:
    image: itzg/bungeecord:latest
    container_name: proxy
    restart: unless-stopped
    user: ${PUID:-1000}:${PGID:-1000}
    stdin_open: true
    tty: true
    environment:
      CFG_DB_PASSWORD: ${DB_PASSWORD:?}
      CFG_DB_USER: ${DB_USER:?}
      CFG_MYSQL_HOST: ${MYSQL_HOST:?}
      CFG_MYSQL_PORT: ${MYSQL_PORT:-3306}
      CFG_POSTGRES_HOST: ${POSTGRES_HOST:?}
      CFG_POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      ENABLE_RCON: "true"
      GID: ${PGID:-1000}
      JVM_XX_OPTS: -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch
      MEMORY: ${PROXY_MEMORY:?}
      REPLACE_ENV_VARIABLES: "true"
      TYPE: ${PROXY_TYPE:-WATERFALL}
      UID: ${PUID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/proxy/config:/config
      - ${BASE_DIR:?}/proxy/data:/server
      - ${BASE_DIR:?}/proxy/logs:/server/logs
      - ${BASE_DIR:?}/proxy/plugins:/plugins
    networks:
      - minecraft
    ports:
      - 25565:25577
    extra_hosts:
      - host.docker.internal:host-gateway
    deploy:
      resources:
        limits:
          cpus: ${PROXY_LIMIT_CPUS:-0}
          memory: ${PROXY_LIMIT_MEM:-0}

  survival:
    image: itzg/minecraft-server:latest
    container_name: survival
    restart: unless-stopped
    user: ${PUID:-1000}:${PGID:-1000}
    stdin_open: true
    tty: true
    environment:
      CFG_DB_PASSWORD: ${DB_PASSWORD:?}
      CFG_DB_USER: ${DB_USER:?}
      CFG_DISCORD_TOKEN: ${DISCORD_TOKEN:?}
      CFG_MYSQL_HOST: ${MYSQL_HOST:?}
      CFG_MYSQL_PORT: ${MYSQL_PORT:-3306}
      CFG_POSTGRES_HOST: ${POSTGRES_HOST:?}
      CFG_POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      COPY_CONFIG_DEST: /data
      ENABLE_ROLLING_LOGS: "true"
      EULA: "true"
      JVM_DD_OPTS: ${JVM_DD_OPTS:-paper.useLegacyPluginLoading=true}
      GID: ${PGID:-1000}
      MEMORY: ${SERVER_MEMORY:?}
      REPLACE_ENV_VARIABLES: "true"
      TYPE: PAPER
      UID: ${PUID:-1000}
      USE_AIKAR_FLAGS: "true"
      VERSION: ${VERSION:-LATEST}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/survival/config:/config
      - ${BASE_DIR:?}/survival/config/server.properties:/server.properties # AntiPopup
      - ${BASE_DIR:?}/survival/data:/data
      - ${BASE_DIR:?}/survival/logs:/data/logs
      - ${BASE_DIR:?}/survival/plugins:/plugins
      - ${BASE_DIR:?}/survival/worlds:/worlds
    networks:
      - minecraft
    extra_hosts:
      - host.docker.internal:host-gateway
    deploy:
      resources:
        limits:
          cpus: ${SERVER_LIMIT_CPUS:-0}
          memory: ${SERVER_LIMIT_MEM:-0}

networks:
  minecraft:
    name: minecraft
