version: "3.9"

services:
  proxy:
    image: itzg/bungeecord:latest
    container_name: proxy
    restart: unless-stopped
    user: ${PUID:-1000}:${PGID:-1000}
    depends_on:
      survival:
        condition: service_healthy
    stdin_open: true
    tty: true
    env_file: .env
    environment:
      ENABLE_RCON: "true"
      GID: ${PGID:-1000}
      JVM_XX_OPTS: -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch
      MEMORY: ${PROXY_MEMORY:?}
      REPLACE_ENV_VARIABLES: "true"
      TYPE: ${PROXY_TYPE:-WATERFALL}
      UID: ${PUID:-1000}
      PATCH_DEFINITIONS: /patches
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/proxy/data:/server
      - ${BASE_DIR:?}/proxy/config:/config
      - ${BASE_DIR:?}/proxy/patches:/patches
      - ${BASE_DIR:?}/proxy/plugins:/server/plugins
      - ${BASE_DIR:?}/proxy/logs:/server/logs
    networks:
      - minecraft
    ports:
      - 25565:25577
    extra_hosts:
      - host.docker.internal:host-gateway
    deploy:
      resources:
        limits:
          cpus: ${PROXY_CPU_LIMIT:-${CPU_LIMIT:-0}}
          memory: ${PROXY_MEM_LIMIT:-${MEM_LIMIT:-0}}

  survival:
    image: itzg/minecraft-server:latest
    container_name: survival
    restart: unless-stopped
    user: ${PUID:-1000}:${PGID:-1000}
    stdin_open: true
    tty: true
    env_file: .env
    environment:
      ENABLE_ROLLING_LOGS: "true"
      EULA: "true"
      JVM_DD_OPTS: ${JVM_DD_OPTS:-paper.useLegacyPluginLoading=true}
      GID: ${PGID:-1000}
      MEMORY: ${SERVER_MEMORY:?}
      REPLACE_ENV_VARIABLES: "true"
      TYPE: PAPER
      UID: ${PUID:-1000}
      USE_AIKAR_FLAGS: "true"
      VERSION: ${VERSION:-LATEST}
      PATCH_DEFINITIONS: /patches
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/survival/data:/data
      - ${BASE_DIR:?}/survival/config:/config
      - ${BASE_DIR:?}/survival/patches:/patches
      - ${BASE_DIR:?}/survival/plugins:/data/plugins
      - ${BASE_DIR:?}/survival/worlds:/worlds
      - ${BASE_DIR:?}/survival/logs:/data/logs
    networks:
      - minecraft
    extra_hosts:
      - host.docker.internal:host-gateway
    deploy:
      resources:
        limits:
          cpus: ${SERVER_CPU_LIMIT:-${CPU_LIMIT:-0}}
          memory: ${SERVER_MEM_LIMIT:-${MEM_LIMIT:-0}}

networks:
  minecraft:
    name: minecraft
