version: "3.9"

services:
  proxy:
    image: itzg/bungeecord:latest
    container_name: proxy
    restart: unless-stopped
    tty: true
    stdin_open: true
    user: ${PUID}:${PGID}
    environment:
      TZ: ${TZ:-UTC}
      UID: ${PUID}
      GID: ${PGID}
      TYPE: WATERFALL
      MEMORY: ${PROXY_MEMORY:-1G}
      JVM_OPTS: -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch
      REPLACE_ENV_VARIABLES: "true"
      ENABLE_RCON: "true"
      CFG_DB_USER: ${DB_USER}
      CFG_DB_PASSWORD: ${DB_PASSWORD}
      CFG_POSTGRES_HOST: ${POSTGRES_HOST}
      CFG_POSTGRES_PORT: ${POSTGRES_PORT}
      CFG_MYSQL_HOST: ${MYSQL_HOST}
      CFG_MYSQL_PORT: ${MYSQL_PORT}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR}/waterfall/data:/server
      - ${BASE_DIR}/waterfall/plugins:/plugins
      - ${BASE_DIR}/waterfall/config:/config
      - ${BASE_DIR}/waterfall/logs:/server/logs
    ports:
      - 25565:25577
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 2G
    labels:
      - diun.enable=true
      - telegram-notifier.monitor=true

  survival:
    image: itzg/minecraft-server:latest
    container_name: survival
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      TZ: ${TZ:-UTC}
      UID: ${PUID}
      GID: ${PGID}
      EULA: "TRUE"
      TYPE: PAPER
      MEMORY: ${SERVER_MEMORY:-8G}
      USE_AIKAR_FLAGS: "true"
      COPY_CONFIG_DEST: /data
      REPLACE_ENV_VARIABLES: "true"
      CFG_DB_USER: ${DB_USER}
      CFG_DB_PASSWORD: ${DB_PASSWORD}
      CFG_POSTGRES_HOST: ${POSTGRES_HOST}
      CFG_POSTGRES_PORT: ${POSTGRES_PORT}
      CFG_MYSQL_HOST: ${MYSQL_HOST}
      CFG_MYSQL_PORT: ${MYSQL_PORT}
      CFG_DISCORD_TOKEN: ${DISCORD_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR}/survival/data:/data
      - ${BASE_DIR}/survival/config:/config
      - ${BASE_DIR}/survival/plugins:/plugins
      - ${BASE_DIR}/survival/worlds:/data/worlds
      - ${MAP_DIR}:/data/plugins/squaremap/web
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 10G
    labels:
      - diun.enable=true
      - telegram-notifier.monitor=true