---
services:
  frigate:
    image: "ghcr.io/blakeblackshear/frigate:stable"
    container_name: "frigate"
    restart: "unless-stopped"
    privileged: true
    env_file:
      - path: ".env"
        required: false
      - path: "stack.env"
        required: false
    environment:
      TZ: "UTC"
    volumes:
      - "${BASE_DIR:-.}/config:/config"
      - "${BASE_DIR:-.}/data:/media/frigate"
    tmpfs:
      - "/dev/shm:size=${FRIGATE_SHM_SIZE:-512M}"
    networks:
      - "frigate"
    ports:
      - 8971:8971
      # - "5000:5000"  # Internal unauthenticated access. Expose carefully.
      - 8554:8554  # RTSP feeds
      - 8555:8555/tcp  # WebRTC over tcp
      - 8555:8555/udp  # WebRTC over udp
    labels:
      - "diun.regopt=ghcr"
    deploy:
      resources:
        limits:
          cpus: "${FRIGATE_CPU_LIMIT:-${CPU_LIMIT:-0}}"
          memory: "${FRIGATE_MEM_LIMIT:-${MEM_LIMIT:-0}}"

networks:
  frigate:
    name: "frigate"
