services:
  rehome:
    image: ghcr.io/thereverend403/rehome:main
    container_name: rehome
    restart: unless-stopped
    init: true
    read_only: true
    user: ${PUID:-1000}:${PGID:-1000}
    env_file: .env
    environment:
      CFG_SECRET_KEY: ${CFG_SECRET_KEY:?}
      CFG_SQLALCHEMY_DATABASE_URI: ${CFG_SQLALCHEMY_DATABASE_URI:?}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/postgresql:/run/postgresql
      - ${BASE_DIR:?}/config:/config
      - ${BASE_DIR:?}/data:/data
    tmpfs:
      - /tmp
    networks:
      - rehome
      - caddy
    labels:
      - diun.regopt=ghcr
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT:-0}
          memory: ${MEM_LIMIT:-0}

networks:
  rehome:
    name: rehome
  caddy:
    external: true
