version: '3.9'

services:
  rehome:
    image: ghcr.io/thereverend403/rehome:latest
    container_name: rehome
    volumes:
      - ${BASE_DIR:?}/config:/config
      - ${BASE_DIR:?}/data:/data
      - ${BASE_DIR:?}/static:/static
      - /etc/localtime:/etc/localtime:ro
      - /var/run/postgresql:/var/run/postgresql
    tmpfs: /run:exec
    ports:
      - 127.0.0.1:5000:5000
    labels:
      - telegram-notifier.monitor=true
    environment:
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY:?}
      FLASK_SENTRY_DSN: ${FLASK_SENTRY_DSN:-}
      FLASK_SQLALCHEMY_DATABASE_URI: ${FLASK_SQLALCHEMY_DATABASE_URI:?}
      GUNICORN_OPTS: ${GUNICORN_OPTS:-}
      PGID: ${PGID:?}
      PUID: ${PUID:?}
      TZ: ${TIMEZONE:-UTC}
    restart: unless-stopped
