version: '3.9'

services:
  rehome:
    image: ghcr.io/thereverend403/rehome:main
    container_name: rehome
    read_only: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/postgresql:/run/postgresql
      - ${BASE_DIR:?}/config:/config
      - ${BASE_DIR:?}/data:/data
      - ${BASE_DIR:?}/static:/static
    tmpfs:
      - /run:exec
      - /tmp
    networks:
      - rehome
    labels:
      - telegram-notifier.monitor=true
    environment:
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY:?}
      FLASK_SENTRY_DSN: ${FLASK_SENTRY_DSN:-}
      FLASK_SQLALCHEMY_DATABASE_URI: ${FLASK_SQLALCHEMY_DATABASE_URI:?}
      GUNICORN_OPTS: ${GUNICORN_OPTS:-}
      PGID: ${PGID:?}
      PUID: ${PUID:?}
    restart: unless-stopped

networks:
  rehome:
    name: rehome
