services:
  rehome:
    image: ghcr.io/thereverend403/rehome:main
    container_name: rehome
    restart: unless-stopped
    init: true
    read_only: true
    user: ${REHOME_PUID:-${PUID:-1000}}:${REHOME_PGID:-${PGID:-1000}}
    env_file: .env
    environment:
      TZ: UTC
      CFG_SECRET_KEY: ${CFG_SECRET_KEY:?}
    volumes:
      - ${BASE_DIR:-.}/config/rehome:/config
      - ${BASE_DIR:-.}/data/rehome:/data
    tmpfs:
      - /tmp
    networks:
      - rehome
      - caddy
    labels:
      - diun.regopt=ghcr
    deploy:
      resources:
        limits:
          cpus: ${REHOME_CPU_LIMIT:-${CPU_LIMIT:-0}}
          memory: ${REHOME_MEM_LIMIT:-${MEM_LIMIT:-0}}

networks:
  rehome:
    name: rehome
  caddy:
    external: true
