services:
  rehome:
    image: ghcr.io/thereverend403/rehome:main
    container_name: rehome
    restart: unless-stopped
    init: true
    read_only: true
    user: ${PUID:-1000}:${PGID:-1000}
    depends_on:
      db-17:
        condition: service_healthy
    env_file: .env
    environment:
      CFG_SECRET_KEY: ${CFG_SECRET_KEY:?}
      CFG_SQLALCHEMY_DATABASE_URI: postgresql+psycopg://${DB_USER:-rehome}:${DB_PASSWORD:?}@${DB_HOST:-}/${DB_NAME:-rehome}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - postgres_17_socket:/run/postgresql
      - ${BASE_DIR:?}/config:/config
      - ${BASE_DIR:?}/data:/data
    tmpfs:
      - /tmp
    networks:
      - rehome
      - caddy
    labels:
      - diun.regopt=ghcr
    deploy:
      resources:
        limits:
          cpus: ${REHOME_CPU_LIMIT:-${CPU_LIMIT:-0}}
          memory: ${REHOME_MEM_LIMIT:-${MEM_LIMIT:-0}}

  db-17:
    image: postgres:17-alpine
    container_name: rehome_db_17
    restart: unless-stopped
    user: ${PUID:?}:${PGID:?}
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    network_mode: "none"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:-.}/data/db/17:/var/lib/postgresql/data
      - ${BASE_DIR:-.}/config/db/17/postgresql.conf:/etc/postgresql.conf
      - postgres_17_socket:/run/postgresql
    tmpfs:
      - /run
    environment:
      POSTGRES_HOST: /run/postgresql
      POSTGRES_DB: ${DB_NAME:-rehome}
      POSTGRES_USER: ${DB_USER:-rehome}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -q --username=$$POSTGRES_USER --host=$$POSTGRES_HOST",
        ]
      start_period: 10s
      start_interval: 1s
      interval: 10s
      timeout: 5s
    deploy:
      resources:
        limits:
          cpus: ${POSTGRES_CPU_LIMIT:-${CPU_LIMIT:-0}}
          memory: ${POSTGRES_MEM_LIMIT:-${MEM_LIMIT:-0}}

volumes:
  postgres_17_socket:

networks:
  rehome:
    name: rehome
  caddy:
    external: true
