version: "3.9"

services:
  znc:
    image: lscr.io/linuxserver/znc:latest
    container_name: znc
    restart: unless-stopped
    network_mode: host
    environment:
      PGID: ${PGID:-1000}
      PUID: ${PUID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/data:/config
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT:-0}
          memory: ${MEM_LIMIT:-0}
