version: "3.9"

services:
  znc:
    image: lscr.io/linuxserver/znc:latest
    container_name: znc
    restart: unless-stopped
    network_mode: host
    environment:
      PGID: ${PGID:?}
      PUID: ${PUID:?}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:?}/data:/config
    labels:
      - telegram-notifier.monitor=true
